name: CI

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Repo
        run: |
          mkdir -p ~/.bin
          curl https://storage.googleapis.com/git-repo-downloads/repo -o ~/.bin/repo
          chmod +x ~/.bin/repo
          echo 'export PATH=$HOME/.bin:$PATH' >> $GITHUB_ENV

      - name: Initialize Repo
        run: repo init -u https://android.googlesource.com/platform/manifest --depth=1

      - name: Sync Repositories
        run: |
          repo sync frameworks/base
          repo sync system/core

      - name: Push to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Add files" || echo "No changes to commit"
          git push -u origin HEAD
